"""add audio_briefing to articles

Revision ID: c816bb69f867
Revises: ae0b1f9fe651
Create Date: 2026-05-12 23:41:34.862200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c816bb69f867'
down_revision: Union[str, None] = 'ae0b1f9fe651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('audio_briefing', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'audio_briefing')
    # ### end Alembic commands ###
