"""add thumbnail_url to articles

Revision ID: 6dc2e3b0a0b3
Revises: c816bb69f867
Create Date: 2026-05-15 15:26:47.797064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc2e3b0a0b3'
down_revision: Union[str, None] = 'c816bb69f867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'thumbnail_url')
    # ### end Alembic commands ###
